[
  { "action": "resetServer" },
  { "action": "createDefaultMaps" },
  { "action": "register", "username": "username1", "password": "password" },
  { "action": "register", "username": "username2", "password": "password" },
  { "action": "login", "username": "username1", "password": "password" },
  { "action": "login", "username": "username2", "password": "password" },
  { "action": "createGame", "sid": 1, "gameName": "game1", "mapId": 1 }
]
